### ISSUE TITLE
Code Reuse

### ISSUE THREAD

**Issue by codegrue** [moononournation/LVGL_Music_Player#2]
Are you sharing code between the 4 version of this project, or do you have copies of the code in each?

**Comment by moononournation** [comment]
Can you describe more what issue you encounter?

**Comment by codegrue** [comment]
Not an issue. Just a question on how you architected it: if you are doing code reuse or maintaining 4 separate projects one for each device.

**Comment by codegrue** [comment]
Not an issue. Just a question on how you architected it: if you are doing code reuse or maintain 4 separate projects one for each device.

**Comment by moononournation** [comment]
separate
