### ISSUE TITLE
wt32-sc01 plus : sketch too big

### ISSUE THREAD

**Issue by CFTechno** [moononournation/LVGL_Music_Player#4]
During the build an error message will appear `Sketch uses 1773669 bytes (135%) of program storage space. Maximum is 1310720 bytes.
Global variables use 96052 bytes (29%) of dynamic memory, leaving 231628 bytes for local variables. Maximum is 327680 bytes.`

The same problem is with the "winamp480x320" sketch but there the build is >140% of the available space

**Comment by moononournation** [comment]
change options in tools menu

**Comment by CFTechno** [comment]
thank you !
